org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.tooling.parallel=true

android.useAndroidX=true
android.r8.gradual.support=true
android.r8.maxWorkers=1

kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=1g
