package dev.ujhhgtg.via.skins

import dev.ujhhgtg.via.R

/** lb.b call-site keys, paired with copied APK drawables (identical PNG SHA-256). */
object SkinIconKeys {
    fun forDrawable(resource: Int): String? = when (resource) {
        R.drawable.address_incognito -> "ic_incognito_mode"
        R.drawable.address_lock -> "ic_lock"
        R.drawable.alert -> "ic_menu_report_abuse"
        R.drawable.android_head -> "ic_menu_open_with"
        R.drawable.arrow_down -> "ic_menu_downloads"
        R.drawable.bars_circle -> "ic_menu_read_aloud"
        R.drawable.briefcase -> "ic_menu_tools"
        R.drawable.chevron_left -> "ic_back"
        R.drawable.chevron_right -> "ic_forward"
        R.drawable.clock -> "ic_history"
        R.drawable.clock_outline -> "ic_menu_history"
        R.drawable.close -> "ic_close"
        R.drawable.code -> "ic_menu_view_source"
        R.drawable.code_window -> "ic_menu_scripts"
        R.drawable.copy -> "ic_menu_rotation"
        R.drawable.curved_arrow_boxed -> "ic_menu_image_mode"
        R.drawable.dots_vertical -> "ic_overflow"
        R.drawable.expand -> "ic_menu_fullscreen"
        R.drawable.favorite_add_icon -> "ic_add"
        R.drawable.favorite_back -> "ic_back"
        R.drawable.find -> "ic_menu_find"
        R.drawable.floppy -> "ic_menu_save"
        R.drawable.folder -> "ic_folder"
        R.drawable.gamepad -> "ic_menu_game_mode"
        R.drawable.ghost -> "ic_menu_incognito_mode"
        R.drawable.globe -> "ic_webpage"
        R.drawable.globe_wireframe -> "ic_menu_site_conf"
        R.drawable.grid -> "ic_menu_customize_menu"
        R.drawable.heart_plus -> "ic_menu_add_favorite"
        R.drawable.house -> "ic_home"
        R.drawable.image -> "ic_image"
        R.drawable.layers -> "ic_menu_offline"
        R.drawable.letter_a_boxed -> "ic_menu_translate"
        R.drawable.letter_t_boxed -> "ic_menu_font_size"
        R.drawable.menu -> "ic_menu"
        R.drawable.menu_next -> "ic_next"
        R.drawable.minus_circle -> "ic_menu_adblock"
        R.drawable.monitor -> "ic_menu_desktop_mode"
        R.drawable.moon -> "ic_menu_night"
        R.drawable.music_note_boxed -> "ic_menu_resource"
        R.drawable.nut -> "ic_menu_settings"
        R.drawable.open_in_new -> "ic_open_external"
        R.drawable.panel_list -> "ic_menu_reader"
        R.drawable.password_dialog_key -> "ic_passwords"
        R.drawable.password_eye_off -> "ic_eye_off"
        R.drawable.password_eye_on -> "ic_eye_on"
        R.drawable.pencil -> "ic_menu_mark"
        R.drawable.phone_boxed -> "ic_menu_useragent"
        R.drawable.plus -> "ic_add"
        R.drawable.power -> "ic_exit"
        R.drawable.printer -> "ic_menu_print"
        R.drawable.pulse_boxed -> "ic_menu_network_log"
        R.drawable.qr_torch -> "ic_torch"
        R.drawable.reader_page_qr -> "ic_qrcode"
        R.drawable.reader_settings -> "ic_settings"
        R.drawable.refresh -> "ic_menu_reload"
        R.drawable.reload -> "ic_reload"
        R.drawable.search -> "ic_search"
        R.drawable.search_collapse -> "ic_collapse_text"
        R.drawable.search_expand -> "ic_expand_text"
        R.drawable.search_favorite -> "ic_favorite"
        R.drawable.search_fill -> "ic_fill_url"
        R.drawable.search_go -> "ic_go"
        R.drawable.search_settings -> "ic_settings"
        R.drawable.search_tab -> "ic_tab"
        R.drawable.share -> "ic_menu_share"
        R.drawable.share_nodes -> "ic_share"
        R.drawable.shortcut_scan_icon -> "ic_scan"
        R.drawable.square_plus -> "ic_menu_add_to_home_screen"
        R.drawable.star -> "ic_bookmark"
        R.drawable.star_plus -> "ic_menu_add_bookmark"
        R.drawable.star_wide -> "ic_menu_bookmark"
        R.drawable.tab_square -> "ic_tabs"
        R.drawable.tab_square_dash -> "ic_menu_scan"
        R.drawable.trash -> "ic_menu_delete"
        R.drawable.trash_tapered -> "ic_delete"
        else -> null
    }
}
