package dev.ujhhgtg.via.downloads

import android.webkit.MimeTypeMap
import java.util.Locale

/** Original ordered MIME overrides from l5.c; first extension wins for duplicate MIME types. */
object DownloadMimeTypes {
    private val entries = listOf(
        "aac" to "audio/aac",
        "abw" to "application/x-abiword",
        "apk" to "application/vnd.android.package-archive",
        "xapk" to "application/xapk-package-archive",
        "arc" to "application/x-freearc",
        "asf" to "video/x-ms-asf",
        "avi" to "video/x-msvideo",
        "azw" to "application/vnd.amazon.ebook",
        "bin" to "application/octet-stream",
        "bmp" to "image/bmp",
        "bz" to "application/x-bzip",
        "bz2" to "application/x-bzip2",
        "bzip2" to "application/x-bzip2",
        "csh" to "application/x-csh",
        "css" to "text/css",
        "csv" to "text/csv",
        "doc" to "application/msword",
        "docx" to "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "eot" to "application/vnd.ms-fontobject",
        "epub" to "application/epub+zip",
        "exe" to "application/octet-stream",
        "gif" to "image/gif",
        "gtar" to "application/x-gtar",
        "gz" to "application/x-gzip",
        "htm" to "text/html",
        "html" to "text/html",
        "mht" to "multipart/related",
        "ico" to "image/vnd.microsoft.icon",
        "ics" to "text/calendar",
        "jar" to "application/java-archive",
        "jpeg" to "image/jpeg",
        "jpg" to "image/jpeg",
        "js" to "text/javascript",
        "json" to "application/json",
        "jsonld" to "application/ld+json",
        "mid" to "audio/midi",
        "midi" to "audio/x-midi",
        "mjs" to "text/javascript",
        "mov" to "video/quicktime",
        "mpc" to "application/vnd.mpohun.certificate",
        "mpe" to "video/mpeg",
        "mpeg" to "video/mpeg",
        "mpg" to "video/mpeg",
        "mpga" to "audio/mpeg",
        "mp4" to "video/mp4",
        "mpkg" to "application/vnd.apple.installer+xml",
        "mp2" to "audio/x-mpeg",
        "mp3" to "audio/mpeg",
        "mp4" to "video/mp4",
        "m3u" to "audio/x-mpegurl",
        "m4a" to "audio/mp4a-latm",
        "m4b" to "audio/mp4a-latm",
        "m4p" to "audio/mp4a-latm",
        "m4u" to "video/vnd.mpegurl",
        "m4v" to "video/x-m4v",
        "odp" to "application/vnd.oasis.opendocument.presentation",
        "ods" to "application/vnd.oasis.opendocument.spreadsheet",
        "odt" to "application/vnd.oasis.opendocument.text",
        "oga" to "audio/ogg",
        "ogg" to "audio/ogg",
        "ogv" to "video/ogg",
        "ogx" to "application/ogg",
        "otf" to "font/otf",
        "png" to "image/png",
        "pdf" to "application/pdf",
        "pps" to "application/vnd.ms-powerpoint",
        "ppt" to "application/vnd.ms-powerpoint",
        "pptx" to "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "rar" to "application/x-rar-compressed",
        "rmvb" to "audio/x-pn-realaudio",
        "rtf" to "application/rtf",
        "sh" to "application/x-sh",
        "svg" to "image/svg+xml",
        "swf" to "application/x-shockwave-flash",
        "tar" to "application/x-tar",
        "tgz" to "application/x-compressed",
        "tif" to "image/tiff",
        "tiff" to "image/tiff",
        "torrent" to "application/x-bittorrent",
        "ttf" to "font/ttf",
        "txt" to "text/plain",
        "vsd" to "application/vnd.visio",
        "wav" to "audio/wav",
        "weba" to "audio/webm",
        "webm" to "video/webm",
        "webp" to "image/webp",
        "wma" to "audio/x-ms-wma",
        "wmv" to "audio/x-ms-wmv",
        "woff" to "font/woff",
        "woff2" to "font/woff2",
        "wps" to "application/vnd.ms-works",
        "xhtml" to "application/xhtml+xml",
        "xls" to "application/vnd.ms-excel",
        "xlsx" to "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "xml" to "text/xml",
        "xul" to "application/vnd.mozilla.xul+xml",
        "z" to "application/x-compress",
        "zip" to "application/zip",
        "3gp" to "video/3gpp",
        "3g2" to "video/3gpp2",
        "7z" to "application/x-7z-compressed",
    )
    fun extension(mime: String?): String? {
        if (mime.isNullOrEmpty()) return null
        return entries.firstOrNull { it.second.equals(mime, true) }?.first
            ?: MimeTypeMap.getSingleton().getExtensionFromMimeType(mime)
    }
    fun mime(extension: String, fallback: String? = null): String? =
        entries.firstOrNull { it.first == extension.lowercase(Locale.ROOT) }?.second
            ?: MimeTypeMap.getSingleton().getMimeTypeFromExtension(extension.lowercase(Locale.ROOT)) ?: fallback
    fun known(extension: String): Boolean = entries.any { it.first.equals(extension, true) }
}
